language: swift
osx_image: xcode7.1
script:
- xctool -workspace GameOfGuilds.xcworkspace -scheme Guilds -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xctool test -workspace GameOfGuilds.xcworkspace -scheme Guilds -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
